THINGS TO DO:

November 22

- COMPLETED: Check zero_one() to make sure it stores BOTH levels of a categorical variable even when `one=` is not being used.

- COMPLETED: Add plot labeling function to avoid needing to use either ggformula or the + pipe with ggplot2

- COMPLETED: Add label_zero_one() automatically to pointplot() when response is zero_one()

November 27

- COMPLETED: Replace remaining calls to ggformula.

- COMPLETED: clone ntiles() from mosaic to avoid dependency

- Arrange for automatic loading of `{ggplot2}` and `{dplyr}`.

December 1

- Add a "signif" option to conf_intervals() that will round to the correct number of digits for each coefficient.


December 3

- YOU WERE LOOKING AT INSTANCES of model_plot() to make sure they are compatible with the new version
as of Dec 2.

- The hospital_sim wasn't working. THIS HAS BEEN FIXED BUT NOT YET CALIBRATED.

December 4

- COMPLETED: Get this to work

```{r}
ForMod <- NHANES::NHANES |>
  dplyr::select(Height, Age, Gender) |>
  dplyr::filter(Age >=15) |>
  dplyr::rename(Sex = Gender)
ForMod |> pointplot(Height ~ splines::ns(Age,3)*Sex, annot = "model", 
                    point_ink = 0.1, model_ink = 1 )

Mod2 <-  ForMod |> model_train(Height ~ splines::ns(Age,3)*Sex) 
model_plot(Mod2, interval="confidence") 
```


- `model_cv()` not working

